# mkdocs serve

site_name: MAS Devops Collection
site_url: https://ibm-mas.github.io/ansible-devops

repo_name: GitHub
repo_url: https://github.com/ibm-mas/ansible-devops
edit_uri: blob/master/docs/

nav:
  - 'Home': index.md
  - 'Full Stack Playbooks':
    - 'IBM Cloud': playbooks/fullstack-roks.md
  - 'Lite Playbooks':
    - 'Core only on IBM Cloud': playbooks/lite-core-roks.md
    - 'Core only on QuickBurn': playbooks/lite-core-quickburn.md
    - 'Manage on IBM Cloud': playbooks/lite-manage-roks.md
  - 'Other Playbooks':
    - 'OCP Playbooks': playbooks/ocp.md
    - 'Dependencies Playbooks': playbooks/dependencies.md
    - 'CP4D Playbooks': playbooks/cp4d.md
    - 'MAS Playbooks': playbooks/mas.md
  - 'Roles':
    - 'amqstreams': roles/amqstreams.md
    - 'ansible_version_check': roles/ansible_version_check.md
    - 'appconnect_install': roles/appconnect_install.md
    - 'cos_setup': roles/cos_setup.md
    - 'cp4d_db2wh': roles/cp4d_db2wh.md
    - 'cp4d_db2wh_backup': roles/cp4d_db2wh_backup.md
    - 'cp4d_db2wh_manage_hack': roles/cp4d_db2wh_manage_hack.md
    - 'cp4d_db2wh_restore': roles/cp4d_db2wh_restore.md
    - 'cp4d_hack_worker_nodes': roles/cp4d_hack_worker_nodes.md
    - 'cp4d_install': roles/cp4d_install.md
    - 'cp4d_install_services': roles/cp4d_install_services.md
    - 'db2u': roles/db2u.md
    - 'gencfg_jdbc': roles/gencfg_jdbc.md
    - 'gencfg_sls': roles/gencfg_sls.md
    - 'gencfg_uds': roles/gencfg_uds.md
    - 'gencfg_workspace': roles/gencfg_workspace.md
    - 'gpu_install': roles/gpu_install.md
    - 'install_operator': roles/install_operator.md
    - 'mongodb': roles/mongodb.md
    - 'ocp_deprovision': roles/ocp_deprovision.md
    - 'ocp_login': roles/ocp_login.md
    - 'ocp_provision': roles/ocp_provision.md
    - 'ocp_setup_github_oauth': roles/ocp_setup_github_oauth.md
    - 'ocp_setup_mas_deps': roles/ocp_setup_mas_deps.md
    - 'ocp_setup_ocs': roles/ocp_setup_ocs.md
    - 'ocp_verify': roles/ocp_verify.md
    - 'sls_install': roles/sls_install.md
    - 'suite_app_configure': roles/suite_app_configure.md
    - 'suite_app_install': roles/suite_app_install.md
    - 'suite_config': roles/suite_config.md
    - 'suite_dns': roles/suite_dns.md
    - 'suite_install': roles/suite_install.md
    - 'suite_mustgather': roles/suite_mustgather.md
    - 'suite_mustgather_download': roles/suite_mustgather_download.md
    - 'suite_verify': roles/suite_verify.md
    - 'uds_install': roles/uds_install.md

theme:
  name: readthedocs
  highlightjs: true
  hljs_languages:
    - yaml
  prev_next_buttons_location: none
extra_css:
  - extra.css
markdown_extensions:
  - toc:
      permalink: 
  - admonition
  # Add this to support expandable sections
  #- pymdownx.details

# https://squidfunk.github.io/mkdocs-material/extensions/admonition/
# Note
# Abstract
# Info
# Tip
# Success
# Question
# Warning
# Failure
# Danger
# Bug
# Example
# Quote
